travel = ["France", "Italy", "Canada", "Maldives", "USA"]
print(travel)
print(sorted(travel))
print(travel)
travel.reverse()
print(travel)
travel.reverse()
print(travel)
travel.sort()
print (travel)
travel.sort(reverse=True)
print(travel)